// fonts.ts
export const fontOptions = [
  { id: "Amatic SC, cursive", label: "Amatic SC" },
  { id: "Anton, sans-serif", label: "Anton" },
  { id: "Alfa Slab One, display", label: "Alfa Slab One" },
  { id: "Arimo, sans-serif", label: "Arimo" },
  { id: "Arvo, serif", label: "Arvo" },
  { id: "Architects Daughter, cursive", label: "Architects Daughter" },
  { id: "Bangers, cursive", label: "Bangers" },
  { id: "Belleza, sans-serif", label: "Belleza" },
  { id: "Bebas Neue, cursive", label: "Bebas Neue" },
  { id: "Bitter, serif", label: "Bitter" },
  { id: "Bree Serif, serif", label: "Bree Serif" },
  { id: "Cabin, sans-serif", label: "Cabin" },
  { id: "Candal, sans-serif", label: "Candal" },
  { id: "Cedarville Cursive, cursive", label: "Cedarville Cursive" },
  { id: "Cousine, monospace", label: "Cousine" },
  { id: "Crimson Text, serif", label: "Crimson Text" },
  { id: "Dancing Script, cursive", label: "Dancing Script" },
  { id: "Dosis, sans-serif", label: "Dosis" },
  { id: "Exo, sans-serif", label: "Exo" },
  { id: "Exo 2, sans-serif", label: "Exo 2" },
  { id: "Fira Mono, monospace", label: "Fira Mono" },
  { id: "Fira Sans, sans-serif", label: "Fira Sans" },
  { id: "Gochi Hand, cursive", label: "Gochi Hand" },
  { id: "Great Vibes, cursive", label: "Great Vibes" },
  { id: "Indie Flower, cursive", label: "Indie Flower" },
  { id: "Inconsolata, monospace", label: "Inconsolata" },
  { id: "Josefin Sans, sans-serif", label: "Josefin Sans" },
  { id: "Josefin Slab, serif", label: "Josefin Slab" },
  { id: "Judson, serif", label: "Judson" },
  { id: "Karla, sans-serif", label: "Karla" },
  { id: "Lato, sans-serif", label: "Lato" },
  { id: "Libre Baskerville, serif", label: "Libre Baskerville" },
  { id: "Lobster, cursive", label: "Lobster" },
  { id: "Lobster Two, cursive", label: "Lobster Two" },
  { id: "Lora, serif", label: "Lora" },
  { id: "Maven Pro, sans-serif", label: "Maven Pro" },
  { id: "Merriweather Sans, sans-serif", label: "Merriweather Sans" },
  { id: "Merriweather, serif", label: "Merriweather" },
  { id: "Noto Sans, sans-serif", label: "Noto Sans" },
  { id: "Open Sans, sans-serif", label: "Open Sans" },
  { id: "Orbitron, sans-serif", label: "Orbitron" },
  { id: "Overpass, sans-serif", label: "Overpass" },
  { id: "PT Sans, sans-serif", label: "PT Sans" },
  { id: "PT Serif, serif", label: "PT Serif" },
  { id: "Pacifico, cursive", label: "Pacifico" },
  { id: "Permanent Marker, cursive", label: "Permanent Marker" },
  { id: "Play, sans-serif", label: "Play" },
  { id: "Playfair Display, serif", label: "Playfair Display" },
  { id: "Playfair, serif", label: "Playfair" },
  { id: "Quattrocento, serif", label: "Quattrocento" },
  { id: "Quicksand, sans-serif", label: "Quicksand" },
  { id: "Raleway Dots, cursive", label: "Raleway Dots" },
  { id: "Raleway, sans-serif", label: "Raleway" },
  { id: "Righteous, cursive", label: "Righteous" },
  { id: "Roboto, sans-serif", label: "Roboto" },
  { id: "Rubik, sans-serif", label: "Rubik" },
  { id: "Saira, sans-serif", label: "Saira" },
  { id: "Satisfy, cursive", label: "Satisfy" },
  { id: "Shadows Into Light, cursive", label: "Shadows Into Light" },
  { id: "Signika, sans-serif", label: "Signika" },
  { id: "Source Sans 3, sans-serif", label: "Source Sans 3" },
  { id: "Source Serif 4, serif", label: "Source Serif 4" },
  { id: "Tangerine, cursive", label: "Tangerine" },
  { id: "Titillium Web, sans-serif", label: "Titillium Web" },
  { id: "Ubuntu, sans-serif", label: "Ubuntu" },
  { id: "UnifrakturMaguntia, cursive", label: "UnifrakturMaguntia" },
  { id: "Varela Round, sans-serif", label: "Varela Round" },
  { id: "Vollkorn, serif", label: "Vollkorn" },
  { id: "Work Sans, sans-serif", label: "Work Sans" },
  { id: "Yanone Kaffeesatz, sans-serif", label: "Yanone Kaffeesatz" },
  { id: "Zilla Slab Highlight, serif", label: "Zilla Slab Highlight" },
  { id: "Zilla Slab, serif", label: "Zilla Slab" },
];
